[package]
name = "local-evm-liquidity"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
curl = "0.4"
hex = "0.4"
primitive-types = { version = "0.11", features = ["serde"] }
revm = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
